###
POST http://localhost:2024/threads/6b7c6d8d-6cc2-44d1-b89e-e30184302795/runs/stream
Content-Type: application/json

{
  "assistant_id": "context_chat",
  "input": {
    "messages": [
      {
        "id": "6b7c6d8d-6cc2-44d1-b89e-e30184302795",
        "type": "user",
        "content": [
          {
            "type": "text",
            "text": "你是谁啊？"
          }
        ]
      }
    ],
    "context": {}
  },
  "config": {
    "streamMode": ["messages"],
    "streamSubgraphs": true,
    "streamResumable": true
  }
}


###
POST http://localhost:2024/runs/stream
Content-Type: application/json

{
  "assistant_id": "context_chat",
  "input": {
    "messages": [
      {
        "role": "user",
        "content": "你是谁啊？"
      }
    ],
    "context": {}
  },
  "stream_mode": ["messages"],
  "stream_subgraphs": true,
  "stream_resumable": true
}