import type { Department, MatchResult } from '@/types/department';

/** 院内基准线（按维度：诊断准确度/方案创新性/风险控制力/协作响应速度/影像分析能力/综合治疗规划） */
export const HOSPITAL_BASELINE = [90, 88, 85, 81, 87, 83];

/** 知识图谱类别 */
export const GRAPH_CATEGORIES = [
  { name: '科室' },
  { name: '疾病' },
  { name: '检查' },
];

/** 医院主色调（知识图谱中按医院区分） */
export const HOSPITAL_COLORS: Record<string, string> = {
  '复旦大学附属肿瘤医院': '#DC2626',   // red-600
  '同济大学附属东方医院': '#2563EB',   // blue-600
  '北京协和医院': '#059669',           // emerald-600
  '复旦大学附属华山医院': '#0D9488',   // teal-600
};

/** 10 个科室 Mock 数据 */
export const mockDepartments: Department[] = [
  // ─── 复旦大学附属肿瘤医院 · 乳腺科 ───
  {
    id: 'fudan-breast',
    name: '乳腺科',
    hospital: '复旦大学附属肿瘤医院',
    icon: '🎗️',
    color: '#DC2626',
    bgColor: 'bg-red-50',
    description: '全国乳腺癌诊治标杆。该科室在 MDT 推理引擎中贡献了海量的分子分型与预后关联数据，在早期诊断与个体化化疗方案决策上具有最高置信度。',
    headDoctor: '吴教授团队',
    memberCount: 42,
    aiScore: 98,
    capability: {
      diagnosticAccuracy: 98,
      solutionInnovation: 92,
      riskControl: 82,
      collaborationSpeed: 88,
      imagingAnalysis: 90,
      treatmentPlanning: 96,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 90, participationCount: 68 },
      { month: '4月', adoptionRate: 92, participationCount: 72 },
      { month: '5月', adoptionRate: 91, participationCount: 75 },
      { month: '6月', adoptionRate: 93, participationCount: 78 },
      { month: '7月', adoptionRate: 94, participationCount: 80 },
      { month: '8月', adoptionRate: 93, participationCount: 82 },
      { month: '9月', adoptionRate: 95, participationCount: 85 },
      { month: '10月', adoptionRate: 96, participationCount: 88 },
      { month: '11月', adoptionRate: 95, participationCount: 90 },
      { month: '12月', adoptionRate: 97, participationCount: 92 },
      { month: '1月', adoptionRate: 96, participationCount: 95 },
      { month: '2月', adoptionRate: 98, participationCount: 98 },
    ],
    knowledgeNodes: [
      { id: 'fb0', name: '乳腺科', category: 0, symbolSize: 55, value: 98 },
      { id: 'fb1', name: '乳腺癌', category: 1, symbolSize: 40, value: 96 },
      { id: 'fb2', name: 'HER2阳性', category: 1, symbolSize: 35, value: 92 },
      { id: 'fb3', name: '三阴性乳腺癌', category: 1, symbolSize: 32, value: 90 },
      { id: 'fb4', name: 'FISH检测', category: 2, symbolSize: 30, value: 94 },
      { id: 'fb5', name: '钼靶', category: 2, symbolSize: 28, value: 88 },
      { id: 'fb6', name: '分子分型', category: 2, symbolSize: 30, value: 95 },
      { id: 'fb7', name: '保乳手术', category: 1, symbolSize: 28, value: 86 },
      { id: 'fb8', name: '乳腺MRI', category: 2, symbolSize: 26, value: 85 },
      { id: 'fb9', name: '新辅助化疗', category: 1, symbolSize: 30, value: 88 },
    ],
    knowledgeEdges: [
      { source: 'fb0', target: 'fb1' }, { source: 'fb0', target: 'fb2' },
      { source: 'fb0', target: 'fb3' }, { source: 'fb0', target: 'fb7' },
      { source: 'fb0', target: 'fb9' },
      { source: 'fb1', target: 'fb4' }, { source: 'fb1', target: 'fb5' },
      { source: 'fb2', target: 'fb4' }, { source: 'fb2', target: 'fb6' },
      { source: 'fb3', target: 'fb6' }, { source: 'fb7', target: 'fb8' },
      { source: 'fb9', target: 'fb6' }, { source: 'fb5', target: 'fb8' },
    ],
    specialties: ['精准保乳手术', '三阴性乳腺癌原研药', '分子分型推理'],
    recentCases: 312,
  },

  // ─── 复旦大学附属肿瘤医院 · 胰腺科 ───
  {
    id: 'fudan-pancreas',
    name: '胰腺科',
    hospital: '复旦大学附属肿瘤医院',
    icon: '🔬',
    color: '#EA580C',
    bgColor: 'bg-orange-50',
    description: '专注于"癌中之王"胰腺癌。其能力库核心在于复杂解剖结构下的手术可切除性评估，通过 AI 融合影像学数据，提供极高精度的血管侵犯判定逻辑。',
    headDoctor: '虞教授团队',
    memberCount: 28,
    aiScore: 96,
    capability: {
      diagnosticAccuracy: 92,
      solutionInnovation: 96,
      riskControl: 90,
      collaborationSpeed: 75,
      imagingAnalysis: 95,
      treatmentPlanning: 88,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 85, participationCount: 42 },
      { month: '4月', adoptionRate: 87, participationCount: 45 },
      { month: '5月', adoptionRate: 86, participationCount: 48 },
      { month: '6月', adoptionRate: 88, participationCount: 50 },
      { month: '7月', adoptionRate: 90, participationCount: 52 },
      { month: '8月', adoptionRate: 89, participationCount: 55 },
      { month: '9月', adoptionRate: 91, participationCount: 58 },
      { month: '10月', adoptionRate: 92, participationCount: 60 },
      { month: '11月', adoptionRate: 93, participationCount: 62 },
      { month: '12月', adoptionRate: 94, participationCount: 65 },
      { month: '1月', adoptionRate: 95, participationCount: 68 },
      { month: '2月', adoptionRate: 96, participationCount: 70 },
    ],
    knowledgeNodes: [
      { id: 'fp0', name: '胰腺科', category: 0, symbolSize: 55, value: 96 },
      { id: 'fp1', name: '胰腺导管腺癌', category: 1, symbolSize: 38, value: 95 },
      { id: 'fp2', name: '壶腹周围癌', category: 1, symbolSize: 30, value: 85 },
      { id: 'fp3', name: '增强CT', category: 2, symbolSize: 32, value: 94 },
      { id: 'fp4', name: 'MRCP', category: 2, symbolSize: 28, value: 88 },
      { id: 'fp5', name: 'EUS-FNA', category: 2, symbolSize: 30, value: 90 },
      { id: 'fp6', name: '血管侵犯评估', category: 1, symbolSize: 35, value: 96 },
      { id: 'fp7', name: '胰腺癌根治术', category: 1, symbolSize: 32, value: 92 },
      { id: 'fp8', name: '新辅助治疗', category: 1, symbolSize: 28, value: 88 },
      { id: 'fp9', name: 'CA19-9', category: 2, symbolSize: 24, value: 80 },
    ],
    knowledgeEdges: [
      { source: 'fp0', target: 'fp1' }, { source: 'fp0', target: 'fp2' },
      { source: 'fp0', target: 'fp6' }, { source: 'fp0', target: 'fp7' },
      { source: 'fp0', target: 'fp8' },
      { source: 'fp1', target: 'fp3' }, { source: 'fp1', target: 'fp5' },
      { source: 'fp2', target: 'fp4' }, { source: 'fp6', target: 'fp3' },
      { source: 'fp7', target: 'fp6' }, { source: 'fp8', target: 'fp9' },
      { source: 'fp5', target: 'fp9' }, { source: 'fp1', target: 'fp9' },
    ],
    specialties: ['"上海方案"', '胰腺癌根治术', '综合新辅助治疗'],
    recentCases: 187,
  },

  // ─── 同济大学附属东方医院 · 重症医学科 (ICU) ───
  {
    id: 'tongji-icu',
    name: '重症医学科',
    hospital: '同济大学附属东方医院',
    icon: '🫀',
    color: '#2563EB',
    bgColor: 'bg-blue-50',
    description: '东方医院的核心学科。在 MDT 引擎中扮演"风险控制官"角色，擅长根据患者实时生理参数推理围术期风险，提供血液动力学监测的动态反馈。',
    headDoctor: '马教授团队',
    memberCount: 35,
    aiScore: 94,
    capability: {
      diagnosticAccuracy: 80,
      solutionInnovation: 78,
      riskControl: 98,
      collaborationSpeed: 95,
      imagingAnalysis: 72,
      treatmentPlanning: 85,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 82, participationCount: 55 },
      { month: '4月', adoptionRate: 84, participationCount: 58 },
      { month: '5月', adoptionRate: 85, participationCount: 60 },
      { month: '6月', adoptionRate: 86, participationCount: 62 },
      { month: '7月', adoptionRate: 88, participationCount: 65 },
      { month: '8月', adoptionRate: 87, participationCount: 68 },
      { month: '9月', adoptionRate: 89, participationCount: 70 },
      { month: '10月', adoptionRate: 90, participationCount: 72 },
      { month: '11月', adoptionRate: 91, participationCount: 75 },
      { month: '12月', adoptionRate: 92, participationCount: 78 },
      { month: '1月', adoptionRate: 93, participationCount: 80 },
      { month: '2月', adoptionRate: 94, participationCount: 82 },
    ],
    knowledgeNodes: [
      { id: 'ti0', name: '重症医学科', category: 0, symbolSize: 55, value: 94 },
      { id: 'ti1', name: 'MODS', category: 1, symbolSize: 35, value: 92 },
      { id: 'ti2', name: 'ARDS', category: 1, symbolSize: 35, value: 90 },
      { id: 'ti3', name: '严重脓毒症', category: 1, symbolSize: 32, value: 88 },
      { id: 'ti4', name: '床旁超声', category: 2, symbolSize: 30, value: 90 },
      { id: 'ti5', name: '血气分析', category: 2, symbolSize: 28, value: 92 },
      { id: 'ti6', name: 'PiCCO监测', category: 2, symbolSize: 28, value: 88 },
      { id: 'ti7', name: 'ECMO', category: 2, symbolSize: 32, value: 95 },
      { id: 'ti8', name: '围术期风险', category: 1, symbolSize: 30, value: 96 },
      { id: 'ti9', name: '血流动力学', category: 1, symbolSize: 28, value: 85 },
    ],
    knowledgeEdges: [
      { source: 'ti0', target: 'ti1' }, { source: 'ti0', target: 'ti2' },
      { source: 'ti0', target: 'ti3' }, { source: 'ti0', target: 'ti8' },
      { source: 'ti0', target: 'ti7' },
      { source: 'ti1', target: 'ti4' }, { source: 'ti1', target: 'ti6' },
      { source: 'ti2', target: 'ti5' }, { source: 'ti2', target: 'ti7' },
      { source: 'ti3', target: 'ti5' }, { source: 'ti8', target: 'ti6' },
      { source: 'ti9', target: 'ti6' }, { source: 'ti9', target: 'ti4' },
    ],
    specialties: ['ECLS/ECMO', '多器官功能支持', '严重脓毒症模拟'],
    recentCases: 245,
  },

  // ─── 同济大学附属东方医院 · 心内科 ───
  {
    id: 'tongji-cardiology',
    name: '心内科',
    hospital: '同济大学附属东方医院',
    icon: '❤️',
    color: '#7C3AED',
    bgColor: 'bg-violet-50',
    description: '以介入心脏病学为特色。其推理逻辑侧重于缺血性心肌病的影响因子分析，在心脏多模态影像（心脏MRI+超声）的综合辅助诊断上具有显著优势。',
    headDoctor: '陈教授团队',
    memberCount: 30,
    aiScore: 93,
    capability: {
      diagnosticAccuracy: 90,
      solutionInnovation: 88,
      riskControl: 85,
      collaborationSpeed: 80,
      imagingAnalysis: 93,
      treatmentPlanning: 78,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 80, participationCount: 50 },
      { month: '4月', adoptionRate: 82, participationCount: 52 },
      { month: '5月', adoptionRate: 83, participationCount: 55 },
      { month: '6月', adoptionRate: 85, participationCount: 58 },
      { month: '7月', adoptionRate: 86, participationCount: 60 },
      { month: '8月', adoptionRate: 87, participationCount: 62 },
      { month: '9月', adoptionRate: 88, participationCount: 65 },
      { month: '10月', adoptionRate: 89, participationCount: 68 },
      { month: '11月', adoptionRate: 90, participationCount: 70 },
      { month: '12月', adoptionRate: 91, participationCount: 72 },
      { month: '1月', adoptionRate: 92, participationCount: 75 },
      { month: '2月', adoptionRate: 93, participationCount: 78 },
    ],
    knowledgeNodes: [
      { id: 'tc0', name: '心内科', category: 0, symbolSize: 55, value: 93 },
      { id: 'tc1', name: '冠心病', category: 1, symbolSize: 38, value: 92 },
      { id: 'tc2', name: '主动脉瓣狭窄', category: 1, symbolSize: 30, value: 88 },
      { id: 'tc3', name: '冠脉造影', category: 2, symbolSize: 32, value: 95 },
      { id: 'tc4', name: '心脏彩超', category: 2, symbolSize: 30, value: 90 },
      { id: 'tc5', name: 'FFR测量', category: 2, symbolSize: 26, value: 85 },
      { id: 'tc6', name: 'PCI', category: 1, symbolSize: 35, value: 94 },
      { id: 'tc7', name: 'TAVR', category: 1, symbolSize: 30, value: 90 },
      { id: 'tc8', name: '心力衰竭', category: 1, symbolSize: 28, value: 86 },
      { id: 'tc9', name: '心脏MRI', category: 2, symbolSize: 28, value: 88 },
    ],
    knowledgeEdges: [
      { source: 'tc0', target: 'tc1' }, { source: 'tc0', target: 'tc2' },
      { source: 'tc0', target: 'tc6' }, { source: 'tc0', target: 'tc7' },
      { source: 'tc0', target: 'tc8' },
      { source: 'tc1', target: 'tc3' }, { source: 'tc1', target: 'tc5' },
      { source: 'tc2', target: 'tc4' }, { source: 'tc6', target: 'tc3' },
      { source: 'tc7', target: 'tc4' }, { source: 'tc8', target: 'tc9' },
      { source: 'tc1', target: 'tc9' }, { source: 'tc5', target: 'tc3' },
    ],
    specialties: ['冠脉介入(PCI)', 'TAVR手术', '心力衰竭数字管理'],
    recentCases: 198,
  },

  // ─── 同济大学附属东方医院 · 泌尿科 ───
  {
    id: 'tongji-urology',
    name: '泌尿科',
    hospital: '同济大学附属东方医院',
    icon: '🤖',
    color: '#0891B2',
    bgColor: 'bg-cyan-50',
    description: '微创技术领先。科室能力库重点集成了前列腺癌病理分级（Gleason评分）与手术路径优化模型，在泌尿系肿瘤的保功能治疗上推理表现卓越。',
    headDoctor: '杨教授团队',
    memberCount: 22,
    aiScore: 91,
    capability: {
      diagnosticAccuracy: 88,
      solutionInnovation: 95,
      riskControl: 80,
      collaborationSpeed: 78,
      imagingAnalysis: 75,
      treatmentPlanning: 85,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 78, participationCount: 35 },
      { month: '4月', adoptionRate: 80, participationCount: 38 },
      { month: '5月', adoptionRate: 82, participationCount: 40 },
      { month: '6月', adoptionRate: 83, participationCount: 42 },
      { month: '7月', adoptionRate: 85, participationCount: 45 },
      { month: '8月', adoptionRate: 84, participationCount: 48 },
      { month: '9月', adoptionRate: 86, participationCount: 50 },
      { month: '10月', adoptionRate: 88, participationCount: 52 },
      { month: '11月', adoptionRate: 89, participationCount: 55 },
      { month: '12月', adoptionRate: 90, participationCount: 58 },
      { month: '1月', adoptionRate: 91, participationCount: 60 },
      { month: '2月', adoptionRate: 92, participationCount: 62 },
    ],
    knowledgeNodes: [
      { id: 'tu0', name: '泌尿科', category: 0, symbolSize: 55, value: 91 },
      { id: 'tu1', name: '前列腺癌', category: 1, symbolSize: 38, value: 94 },
      { id: 'tu2', name: '肾细胞癌', category: 1, symbolSize: 32, value: 88 },
      { id: 'tu3', name: 'mpMRI', category: 2, symbolSize: 30, value: 90 },
      { id: 'tu4', name: 'PSA', category: 2, symbolSize: 26, value: 85 },
      { id: 'tu5', name: '达芬奇机器人', category: 2, symbolSize: 35, value: 96 },
      { id: 'tu6', name: 'Gleason评分', category: 1, symbolSize: 30, value: 92 },
      { id: 'tu7', name: '精准消融', category: 1, symbolSize: 28, value: 88 },
      { id: 'tu8', name: '尿路重建', category: 1, symbolSize: 26, value: 82 },
    ],
    knowledgeEdges: [
      { source: 'tu0', target: 'tu1' }, { source: 'tu0', target: 'tu2' },
      { source: 'tu0', target: 'tu5' }, { source: 'tu0', target: 'tu7' },
      { source: 'tu0', target: 'tu8' },
      { source: 'tu1', target: 'tu3' }, { source: 'tu1', target: 'tu4' },
      { source: 'tu1', target: 'tu6' }, { source: 'tu2', target: 'tu3' },
      { source: 'tu5', target: 'tu7' }, { source: 'tu6', target: 'tu4' },
    ],
    specialties: ['达芬奇机器人手术', '前列腺癌精准消融', '尿路重建'],
    recentCases: 156,
  },

  // ─── 北京协和医院 · 眼科 ───
  {
    id: 'peking-ophthalmology',
    name: '眼科',
    hospital: '北京协和医院',
    icon: '👁️',
    color: '#059669',
    bgColor: 'bg-emerald-50',
    description: '协和眼科是中国眼科学的摇篮。其能力模型在罕见眼底病变与系统性疾病的眼部表现推理中具有不可替代性，是处理跨学科复杂眼病决策的核心。',
    headDoctor: '陈教授团队',
    memberCount: 38,
    aiScore: 97,
    capability: {
      diagnosticAccuracy: 97,
      solutionInnovation: 80,
      riskControl: 75,
      collaborationSpeed: 70,
      imagingAnalysis: 96,
      treatmentPlanning: 68,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 88, participationCount: 60 },
      { month: '4月', adoptionRate: 89, participationCount: 62 },
      { month: '5月', adoptionRate: 90, participationCount: 65 },
      { month: '6月', adoptionRate: 91, participationCount: 68 },
      { month: '7月', adoptionRate: 92, participationCount: 70 },
      { month: '8月', adoptionRate: 93, participationCount: 72 },
      { month: '9月', adoptionRate: 94, participationCount: 75 },
      { month: '10月', adoptionRate: 93, participationCount: 78 },
      { month: '11月', adoptionRate: 95, participationCount: 80 },
      { month: '12月', adoptionRate: 96, participationCount: 82 },
      { month: '1月', adoptionRate: 97, participationCount: 85 },
      { month: '2月', adoptionRate: 97, participationCount: 88 },
    ],
    knowledgeNodes: [
      { id: 'po0', name: '眼科', category: 0, symbolSize: 55, value: 97 },
      { id: 'po1', name: '视网膜脱离', category: 1, symbolSize: 35, value: 92 },
      { id: 'po2', name: '黄斑变性', category: 1, symbolSize: 35, value: 90 },
      { id: 'po3', name: '葡萄膜炎', category: 1, symbolSize: 32, value: 94 },
      { id: 'po4', name: 'OCT', category: 2, symbolSize: 32, value: 96 },
      { id: 'po5', name: '眼底荧光造影', category: 2, symbolSize: 30, value: 92 },
      { id: 'po6', name: '视觉电生理', category: 2, symbolSize: 26, value: 85 },
      { id: 'po7', name: 'AI读片', category: 2, symbolSize: 30, value: 95 },
      { id: 'po8', name: '疑难眼底病', category: 1, symbolSize: 30, value: 96 },
    ],
    knowledgeEdges: [
      { source: 'po0', target: 'po1' }, { source: 'po0', target: 'po2' },
      { source: 'po0', target: 'po3' }, { source: 'po0', target: 'po8' },
      { source: 'po1', target: 'po4' }, { source: 'po1', target: 'po5' },
      { source: 'po2', target: 'po4' }, { source: 'po2', target: 'po7' },
      { source: 'po3', target: 'po5' }, { source: 'po3', target: 'po6' },
      { source: 'po8', target: 'po7' }, { source: 'po4', target: 'po7' },
    ],
    specialties: ['葡萄膜炎诊断', '疑难眼底病', '眼科AI读片验证'],
    recentCases: 276,
  },

  // ─── 复旦大学附属华山医院 · 旅行医学科 ───
  {
    id: 'huashan-travel',
    name: '旅行医学科',
    hospital: '复旦大学附属华山医院',
    icon: '🌍',
    color: '#0D9488',
    bgColor: 'bg-teal-50',
    description: '依托华山感染的国家级科研能力，该科室在 MDT 引擎中主要负责"外部环境风险因子"的输入。它能根据出行目的地（如非洲、南美等）的实时流行病学数据，自动推理出所需的强制性与建议性防疫方案。',
    headDoctor: '张文宏教授团队',
    memberCount: 25,
    aiScore: 95,
    capability: {
      diagnosticAccuracy: 92,
      solutionInnovation: 97,
      riskControl: 98,
      collaborationSpeed: 90,
      imagingAnalysis: 96,
      treatmentPlanning: 72,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 82, participationCount: 35 },
      { month: '4月', adoptionRate: 85, participationCount: 40 },
      { month: '5月', adoptionRate: 87, participationCount: 48 },
      { month: '6月', adoptionRate: 92, participationCount: 65 },
      { month: '7月', adoptionRate: 95, participationCount: 78 },
      { month: '8月', adoptionRate: 96, participationCount: 82 },
      { month: '9月', adoptionRate: 90, participationCount: 58 },
      { month: '10月', adoptionRate: 93, participationCount: 70 },
      { month: '11月', adoptionRate: 88, participationCount: 45 },
      { month: '12月', adoptionRate: 86, participationCount: 42 },
      { month: '1月', adoptionRate: 91, participationCount: 60 },
      { month: '2月', adoptionRate: 94, participationCount: 72 },
    ],
    knowledgeNodes: [
      { id: 'ht0', name: '华山旅行医学', category: 0, symbolSize: 55, value: 95 },
      { id: 'ht1', name: '黄热病', category: 1, symbolSize: 35, value: 94 },
      { id: 'ht2', name: '疟疾', category: 1, symbolSize: 38, value: 96 },
      { id: 'ht3', name: '霍乱', category: 1, symbolSize: 30, value: 88 },
      { id: 'ht4', name: '登革热', category: 1, symbolSize: 32, value: 90 },
      { id: 'ht5', name: '海拔性疾病', category: 1, symbolSize: 28, value: 85 },
      { id: 'ht6', name: '疫苗接种记录检查', category: 2, symbolSize: 32, value: 95 },
      { id: 'ht7', name: '抗体水平检测', category: 2, symbolSize: 30, value: 92 },
      { id: 'ht8', name: '预防性药物方案', category: 2, symbolSize: 30, value: 94 },
      { id: 'ht9', name: '电子疫苗证', category: 2, symbolSize: 26, value: 88 },
    ],
    knowledgeEdges: [
      { source: 'ht0', target: 'ht1' }, { source: 'ht0', target: 'ht2' },
      { source: 'ht0', target: 'ht3' }, { source: 'ht0', target: 'ht4' },
      { source: 'ht0', target: 'ht5' },
      { source: 'ht1', target: 'ht6' }, { source: 'ht1', target: 'ht7' },
      { source: 'ht2', target: 'ht8' }, { source: 'ht2', target: 'ht7' },
      { source: 'ht3', target: 'ht6' }, { source: 'ht4', target: 'ht8' },
      { source: 'ht5', target: 'ht8' }, { source: 'ht6', target: 'ht9' },
      { source: 'ht7', target: 'ht9' },
    ],
    specialties: ['海外疫情实时监控', '个体化疫苗接种方案', '热带病风险推理'],
    recentCases: 208,
  },

  // ─── 同济大学附属东方医院 · 全科医学科 ───
  {
    id: 'tongji-general',
    name: '全科医学科',
    hospital: '同济大学附属东方医院',
    icon: '🏠',
    color: '#0EA5E9',
    bgColor: 'bg-sky-50',
    description: '作为东方医院的"守门人"，全科医学科在强推理引擎中负责首诊逻辑校准。其核心价值在于多病共存患者的系统性评估与精准分诊，是基层医疗决策支持系统的核心节点。',
    headDoctor: '刘教授团队',
    memberCount: 32,
    aiScore: 86,
    capability: {
      diagnosticAccuracy: 85,
      solutionInnovation: 78,
      riskControl: 92,
      collaborationSpeed: 95,
      imagingAnalysis: 70,
      treatmentPlanning: 82,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 78, participationCount: 32 },
      { month: '4月', adoptionRate: 80, participationCount: 35 },
      { month: '5月', adoptionRate: 79, participationCount: 38 },
      { month: '6月', adoptionRate: 82, participationCount: 40 },
      { month: '7月', adoptionRate: 83, participationCount: 42 },
      { month: '8月', adoptionRate: 81, participationCount: 45 },
      { month: '9月', adoptionRate: 84, participationCount: 48 },
      { month: '10月', adoptionRate: 85, participationCount: 50 },
      { month: '11月', adoptionRate: 83, participationCount: 52 },
      { month: '12月', adoptionRate: 86, participationCount: 55 },
      { month: '1月', adoptionRate: 87, participationCount: 58 },
      { month: '2月', adoptionRate: 88, participationCount: 60 },
    ],
    knowledgeNodes: [
      { id: 'tg0', name: '全科医学科', category: 0, symbolSize: 55, value: 86 },
      { id: 'tg1', name: '糖尿病', category: 1, symbolSize: 38, value: 90 },
      { id: 'tg2', name: '高血压', category: 1, symbolSize: 38, value: 92 },
      { id: 'tg3', name: '未分化疾病', category: 1, symbolSize: 32, value: 85 },
      { id: 'tg4', name: '首诊负责制', category: 1, symbolSize: 30, value: 88 },
      { id: 'tg5', name: '慢阻肺', category: 1, symbolSize: 28, value: 82 },
      { id: 'tg6', name: '血糖监测', category: 2, symbolSize: 28, value: 88 },
      { id: 'tg7', name: '动态血压', category: 2, symbolSize: 26, value: 85 },
      { id: 'tg8', name: '全科诊疗路径', category: 2, symbolSize: 30, value: 90 },
      { id: 'tg9', name: '社区转诊评估', category: 2, symbolSize: 28, value: 86 },
    ],
    knowledgeEdges: [
      { source: 'tg0', target: 'tg1' }, { source: 'tg0', target: 'tg2' },
      { source: 'tg0', target: 'tg3' }, { source: 'tg0', target: 'tg4' },
      { source: 'tg0', target: 'tg5' },
      { source: 'tg1', target: 'tg6' }, { source: 'tg2', target: 'tg7' },
      { source: 'tg3', target: 'tg8' }, { source: 'tg4', target: 'tg9' },
      { source: 'tg5', target: 'tg8' }, { source: 'tg1', target: 'tg8' },
      { source: 'tg2', target: 'tg8' }, { source: 'tg9', target: 'tg8' },
    ],
    specialties: ['多病共存管理', '疑难杂症初筛', '全人全过程照顾'],
    recentCases: 380,
  },

  // ─── 同济大学附属东方医院 · 老年病科 ───
  {
    id: 'tongji-geriatrics',
    name: '老年病科',
    hospital: '同济大学附属东方医院',
    icon: '🌳',
    color: '#92400E',
    bgColor: 'bg-amber-50',
    description: '针对上海老龄化特色，该科室在引擎中引入了"衰弱评估模型"。它能自动推理出手术对高龄患者的耐受度，有效降低术后并发症风险，是MDT中高龄患者决策的关键守护者。',
    headDoctor: '周教授团队',
    memberCount: 26,
    aiScore: 84,
    capability: {
      diagnosticAccuracy: 80,
      solutionInnovation: 80,
      riskControl: 94,
      collaborationSpeed: 78,
      imagingAnalysis: 68,
      treatmentPlanning: 96,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 80, participationCount: 40 },
      { month: '4月', adoptionRate: 79, participationCount: 42 },
      { month: '5月', adoptionRate: 81, participationCount: 44 },
      { month: '6月', adoptionRate: 82, participationCount: 46 },
      { month: '7月', adoptionRate: 80, participationCount: 48 },
      { month: '8月', adoptionRate: 83, participationCount: 50 },
      { month: '9月', adoptionRate: 84, participationCount: 52 },
      { month: '10月', adoptionRate: 82, participationCount: 55 },
      { month: '11月', adoptionRate: 85, participationCount: 58 },
      { month: '12月', adoptionRate: 86, participationCount: 60 },
      { month: '1月', adoptionRate: 84, participationCount: 62 },
      { month: '2月', adoptionRate: 87, participationCount: 65 },
    ],
    knowledgeNodes: [
      { id: 'te0', name: '老年病科', category: 0, symbolSize: 55, value: 84 },
      { id: 'te1', name: '衰弱', category: 1, symbolSize: 38, value: 96 },
      { id: 'te2', name: '肌少症', category: 1, symbolSize: 32, value: 88 },
      { id: 'te3', name: '认知障碍', category: 1, symbolSize: 35, value: 90 },
      { id: 'te4', name: '多重用药', category: 1, symbolSize: 35, value: 94 },
      { id: 'te5', name: '跌倒风险', category: 1, symbolSize: 28, value: 85 },
      { id: 'te6', name: '衰弱指数评估', category: 2, symbolSize: 32, value: 96 },
      { id: 'te7', name: '简易认知量表', category: 2, symbolSize: 28, value: 88 },
      { id: 'te8', name: '药物相互作用检测', category: 2, symbolSize: 30, value: 92 },
      { id: 'te9', name: '营养状态评估', category: 2, symbolSize: 26, value: 82 },
    ],
    knowledgeEdges: [
      { source: 'te0', target: 'te1' }, { source: 'te0', target: 'te2' },
      { source: 'te0', target: 'te3' }, { source: 'te0', target: 'te4' },
      { source: 'te0', target: 'te5' },
      { source: 'te1', target: 'te6' }, { source: 'te1', target: 'te9' },
      { source: 'te2', target: 'te9' }, { source: 'te3', target: 'te7' },
      { source: 'te4', target: 'te8' }, { source: 'te5', target: 'te6' },
      { source: 'te5', target: 'te7' }, { source: 'te4', target: 'te6' },
    ],
    specialties: ['老年综合征评估', '衰弱指数推理', '多药合用干预'],
    recentCases: 165,
  },

  // ─── 同济大学附属东方医院 · 健康管理科 ───
  {
    id: 'tongji-health',
    name: '健康管理科',
    hospital: '同济大学附属东方医院',
    icon: '🛡️',
    color: '#16A34A',
    bgColor: 'bg-green-50',
    description: '依托东方医院强大的体检大数据，该科室在引擎中负责"检后闭环推理"。其模型能根据历年体检指标的细微变化，提前3-6个月预警潜在的重大疾病风险，是预防医学决策的数据中枢。',
    headDoctor: '林教授团队',
    memberCount: 20,
    aiScore: 82,
    capability: {
      diagnosticAccuracy: 78,
      solutionInnovation: 90,
      riskControl: 75,
      collaborationSpeed: 85,
      imagingAnalysis: 88,
      treatmentPlanning: 76,
    },
    monthlyDecisions: [
      { month: '3月', adoptionRate: 78, participationCount: 45 },
      { month: '4月', adoptionRate: 80, participationCount: 48 },
      { month: '5月', adoptionRate: 82, participationCount: 50 },
      { month: '6月', adoptionRate: 79, participationCount: 52 },
      { month: '7月', adoptionRate: 81, participationCount: 55 },
      { month: '8月', adoptionRate: 83, participationCount: 58 },
      { month: '9月', adoptionRate: 80, participationCount: 60 },
      { month: '10月', adoptionRate: 84, participationCount: 62 },
      { month: '11月', adoptionRate: 85, participationCount: 65 },
      { month: '12月', adoptionRate: 82, participationCount: 68 },
      { month: '1月', adoptionRate: 86, participationCount: 70 },
      { month: '2月', adoptionRate: 88, participationCount: 72 },
    ],
    knowledgeNodes: [
      { id: 'tm0', name: '健康管理科', category: 0, symbolSize: 55, value: 82 },
      { id: 'tm1', name: '肺结节随访', category: 1, symbolSize: 35, value: 90 },
      { id: 'tm2', name: '代谢综合征', category: 1, symbolSize: 35, value: 88 },
      { id: 'tm3', name: '癌症早筛', category: 1, symbolSize: 32, value: 86 },
      { id: 'tm4', name: '体检报告解读', category: 1, symbolSize: 30, value: 85 },
      { id: 'tm5', name: '慢性病预警', category: 1, symbolSize: 28, value: 82 },
      { id: 'tm6', name: '低剂量CT', category: 2, symbolSize: 30, value: 90 },
      { id: 'tm7', name: '风险评分模型', category: 2, symbolSize: 32, value: 92 },
      { id: 'tm8', name: '生活方式处方', category: 2, symbolSize: 28, value: 88 },
      { id: 'tm9', name: '数字健康档案', category: 2, symbolSize: 26, value: 85 },
    ],
    knowledgeEdges: [
      { source: 'tm0', target: 'tm1' }, { source: 'tm0', target: 'tm2' },
      { source: 'tm0', target: 'tm3' }, { source: 'tm0', target: 'tm4' },
      { source: 'tm0', target: 'tm5' },
      { source: 'tm1', target: 'tm6' }, { source: 'tm1', target: 'tm7' },
      { source: 'tm2', target: 'tm8' }, { source: 'tm3', target: 'tm7' },
      { source: 'tm4', target: 'tm9' }, { source: 'tm5', target: 'tm7' },
      { source: 'tm5', target: 'tm8' }, { source: 'tm9', target: 'tm7' },
    ],
    specialties: ['检后风险追踪', '慢性病早筛', '生活方式干预模型'],
    recentCases: 420,
  },
];

/** 匹配规则 lookup */
const MATCHING_RULES: Record<string, MatchResult[]> = {
  '乳腺癌': [
    { departmentId: 'fudan-breast', score: 98, reason: '复旦肿瘤乳腺科在分子分型推理与个体化化疗方案决策上具有最高置信度，诊断准确度98分，是乳腺癌MDT的首选核心科室。' },
    { departmentId: 'peking-ophthalmology', score: 55, reason: '协和眼科可协助评估乳腺癌相关副瘤综合征的眼部表现，在跨学科鉴别诊断中有辅助价值。' },
    { departmentId: 'tongji-icu', score: 52, reason: '重症医学科可为乳腺癌高危患者提供围术期风险评估和术后监护支持。' },
    { departmentId: 'fudan-pancreas', score: 45, reason: '胰腺科在多原发癌的鉴别诊断中可提供参考经验。' },
    { departmentId: 'tongji-cardiology', score: 42, reason: '心内科可评估化疗相关心脏毒性风险（如蒽环类药物），协助制定心脏安全方案。' },
    { departmentId: 'tongji-geriatrics', score: 38, reason: '老年病科可为高龄乳腺癌患者进行衰弱评估，判断化疗与手术耐受度。' },
    { departmentId: 'tongji-health', score: 32, reason: '健康管理科在乳腺癌筛查（钼靶随访）和康复期健康管理中可提供数据支持。' },
    { departmentId: 'tongji-urology', score: 30, reason: '泌尿科在乳腺癌相关病例中参与度较低，仅在极罕见的泌尿系转移时介入。' },
    { departmentId: 'tongji-general', score: 25, reason: '全科医学科可在乳腺癌患者的社区随访和多病共存管理中提供基层支持。' },
    { departmentId: 'huashan-travel', score: 22, reason: '旅行医学科在乳腺癌病例中无直接相关性，仅在患者需出境就医时可提供旅行健康评估。' },
  ],
  '胰腺癌': [
    { departmentId: 'fudan-pancreas', score: 97, reason: '复旦肿瘤胰腺科首创"上海方案"，在血管侵犯判定和可切除性AI评估中具有96分方案创新性，是胰腺癌MDT的绝对核心。' },
    { departmentId: 'tongji-icu', score: 88, reason: '重症医学科风险控制力98分，胰腺癌根治术后并发症管理和围术期生命支持不可或缺。' },
    { departmentId: 'fudan-breast', score: 60, reason: '乳腺科在消化系统肿瘤的分子分型交叉研究中有一定参考价值。' },
    { departmentId: 'tongji-cardiology', score: 55, reason: '心内科可评估胰腺癌患者术前心功能，降低围术期心血管事件风险。' },
    { departmentId: 'tongji-geriatrics', score: 42, reason: '老年病科可为高龄胰腺癌患者评估手术耐受度和多重用药风险。' },
    { departmentId: 'tongji-urology', score: 40, reason: '泌尿科在胰腺癌累及肾脏或输尿管时可提供联合手术支持。' },
    { departmentId: 'peking-ophthalmology', score: 25, reason: '眼科在胰腺癌相关病例中参与度极低。' },
    { departmentId: 'tongji-health', score: 22, reason: '健康管理科可在胰腺癌高危人群的早期筛查和CA19-9追踪中提供预警。' },
    { departmentId: 'tongji-general', score: 20, reason: '全科医学科可在胰腺癌患者的首诊识别和转诊中发挥分诊作用。' },
    { departmentId: 'huashan-travel', score: 18, reason: '旅行医学科在胰腺癌病例中无直接相关性。' },
  ],
  '冠心病': [
    { departmentId: 'tongji-cardiology', score: 96, reason: '东方医院心内科以冠脉介入(PCI)为特色，冠脉造影+FFR精准评估能力突出，是冠心病MDT的核心决策者。' },
    { departmentId: 'tongji-icu', score: 90, reason: '重症医学科在急性心梗后血流动力学支持、ECMO辅助中具有98分风险控制力，是危重冠心病的生命保障。' },
    { departmentId: 'tongji-general', score: 62, reason: '全科医学科在冠心病慢病管理、社区随访和危急重症早期识别中发挥"守门人"作用，协作响应速度95分。' },
    { departmentId: 'peking-ophthalmology', score: 58, reason: '协和眼科可通过眼底血管评估反映全身动脉硬化程度，为冠心病系统性评估提供辅助证据。' },
    { departmentId: 'tongji-geriatrics', score: 58, reason: '老年病科可为高龄冠心病患者评估衰弱指数和手术耐受度，优化术后康复方案。' },
    { departmentId: 'tongji-health', score: 48, reason: '健康管理科可通过历年体检数据追踪心血管风险因子变化，实现冠心病早期预警。' },
    { departmentId: 'huashan-travel', score: 38, reason: '旅行医学科可评估冠心病患者出行风险，针对高海拔或长途飞行提供心血管安全建议。' },
    { departmentId: 'tongji-urology', score: 35, reason: '泌尿科在冠心病合并泌尿系手术时可协同评估手术耐受性。' },
    { departmentId: 'fudan-breast', score: 30, reason: '乳腺科在冠心病相关决策中参与度较低。' },
    { departmentId: 'fudan-pancreas', score: 28, reason: '胰腺科在冠心病相关决策中参与度较低。' },
  ],
  '前列腺癌': [
    { departmentId: 'tongji-urology', score: 97, reason: '东方医院泌尿科达芬奇机器人手术经验丰富，Gleason评分与手术路径优化模型是前列腺癌精准治疗的核心。' },
    { departmentId: 'tongji-icu', score: 65, reason: '重症医学科可为高龄前列腺癌患者提供围术期风险控制和术后生命支持。' },
    { departmentId: 'tongji-cardiology', score: 55, reason: '心内科可评估前列腺癌患者（多为高龄）的心功能，优化围术期心脏管理。' },
    { departmentId: 'tongji-geriatrics', score: 52, reason: '老年病科在高龄前列腺癌患者的衰弱评估和多药管理中具有关键辅助价值。' },
    { departmentId: 'fudan-breast', score: 40, reason: '乳腺科在激素受体相关的交叉研究中有一定分子通路参考价值。' },
    { departmentId: 'tongji-health', score: 38, reason: '健康管理科可在PSA追踪和前列腺癌高危人群筛查中提供数据预警。' },
    { departmentId: 'fudan-pancreas', score: 30, reason: '胰腺科在前列腺癌病例中参与度较低。' },
    { departmentId: 'tongji-general', score: 28, reason: '全科医学科在前列腺癌患者的社区随访和多病共存管理中可发挥基层协调作用。' },
    { departmentId: 'peking-ophthalmology', score: 25, reason: '眼科在前列腺癌相关决策中参与度极低。' },
    { departmentId: 'huashan-travel', score: 15, reason: '旅行医学科在前列腺癌病例中无直接相关性。' },
  ],
  '视网膜脱离': [
    { departmentId: 'peking-ophthalmology', score: 98, reason: '协和眼科诊断准确度97分、影像分析能力96分，OCT+眼底荧光造影+AI读片的综合能力在视网膜疾病中无可替代。' },
    { departmentId: 'tongji-icu', score: 45, reason: '重症医学科在复杂眼科手术的全麻管理和高危患者监护中可提供支持。' },
    { departmentId: 'tongji-cardiology', score: 40, reason: '心内科可评估视网膜脱离患者是否存在高血压性血管病变等系统性因素。' },
    { departmentId: 'tongji-geriatrics', score: 25, reason: '老年病科可为高龄视网膜脱离患者评估手术耐受度和术后跌倒风险。' },
    { departmentId: 'fudan-breast', score: 20, reason: '乳腺科在视网膜脱离病例中无直接相关性。' },
    { departmentId: 'tongji-health', score: 20, reason: '健康管理科可在体检中通过眼底筛查发现早期视网膜病变。' },
    { departmentId: 'fudan-pancreas', score: 18, reason: '胰腺科在视网膜脱离病例中无直接相关性。' },
    { departmentId: 'tongji-general', score: 18, reason: '全科医学科可在视网膜脱离患者的首诊识别和转诊中发挥分诊作用。' },
    { departmentId: 'tongji-urology', score: 15, reason: '泌尿科在视网膜脱离病例中无直接相关性。' },
    { departmentId: 'huashan-travel', score: 12, reason: '旅行医学科在视网膜脱离病例中无直接相关性。' },
  ],
  '疟疾': [
    { departmentId: 'huashan-travel', score: 99, reason: '华山旅行医学科风险控制力98分、方案创新性97分，系统能自动抓取WHO实时数据，结合患者既往疫苗史，输出0秒延迟的防疫处方，是疟疾防治MDT的绝对核心。' },
    { departmentId: 'tongji-icu', score: 78, reason: '重症医学科在重症疟疾（脑型疟疾）的生命支持和多器官功能衰竭管理中不可或缺。' },
    { departmentId: 'peking-ophthalmology', score: 35, reason: '协和眼科可评估疟疾相关的视网膜病变（疟疾性视网膜病），协助判断脑型疟疾严重程度。' },
    { departmentId: 'tongji-cardiology', score: 32, reason: '心内科可评估疟疾引起的心肌炎等心脏并发症风险。' },
    { departmentId: 'tongji-general', score: 28, reason: '全科医学科可在疟疾的首诊识别和发热鉴别诊断中发挥分诊作用。' },
    { departmentId: 'tongji-geriatrics', score: 22, reason: '老年病科可为高龄疟疾患者评估并发症风险和药物耐受度。' },
    { departmentId: 'tongji-health', score: 18, reason: '健康管理科可在出境体检中提供疟疾风险预评估。' },
    { departmentId: 'fudan-breast', score: 15, reason: '乳腺科在疟疾相关病例中无直接相关性。' },
    { departmentId: 'fudan-pancreas', score: 15, reason: '胰腺科在疟疾相关病例中无直接相关性。' },
    { departmentId: 'tongji-urology', score: 12, reason: '泌尿科在疟疾相关病例中无直接相关性。' },
  ],
  '糖尿病': [
    { departmentId: 'tongji-general', score: 95, reason: '全科医学科是糖尿病慢病管理的核心，协作响应95分，在多病共存患者的血糖控制和长期随访中具有首诊负责制优势。' },
    { departmentId: 'tongji-geriatrics', score: 88, reason: '老年病科综合治疗规划96分，在高龄糖尿病患者的多重用药干预和衰弱评估中具有不可替代的价值。' },
    { departmentId: 'tongji-health', score: 85, reason: '健康管理科方案创新性90分，通过历年体检数据的血糖趋势分析，可提前3-6个月预警糖尿病进展风险。' },
    { departmentId: 'tongji-cardiology', score: 72, reason: '心内科可评估糖尿病相关的心血管并发症风险（冠心病、心力衰竭），协助制定心脏保护方案。' },
    { departmentId: 'peking-ophthalmology', score: 68, reason: '协和眼科可通过OCT和眼底AI读片评估糖尿病视网膜病变分期，是糖尿病并发症监测的关键环节。' },
    { departmentId: 'tongji-icu', score: 55, reason: '重症医学科可处理糖尿病酮症酸中毒(DKA)和高渗高血糖综合征(HHS)等危急重症。' },
    { departmentId: 'huashan-travel', score: 42, reason: '旅行医学科可为糖尿病患者的出行提供血糖管理方案和胰岛素携带指导。' },
    { departmentId: 'tongji-urology', score: 35, reason: '泌尿科在糖尿病相关泌尿系感染和神经源性膀胱的管理中可提供协助。' },
    { departmentId: 'fudan-pancreas', score: 30, reason: '胰腺科在胰源性糖尿病（3c型）的鉴别诊断中有一定参考价值。' },
    { departmentId: 'fudan-breast', score: 20, reason: '乳腺科在糖尿病相关病例中参与度较低。' },
  ],
};

/** 获取匹配结果 */
export function getMatchResults(query: string): MatchResult[] {
  const trimmed = query.trim();

  // 精确匹配
  if (MATCHING_RULES[trimmed]) {
    return MATCHING_RULES[trimmed];
  }

  // 部分匹配（查找包含关键词的规则）
  for (const key of Object.keys(MATCHING_RULES)) {
    if (trimmed.includes(key) || key.includes(trimmed)) {
      return MATCHING_RULES[key];
    }
  }

  // 默认：基于 AI 综合评分 + 随机波动
  return mockDepartments
    .map((dept) => ({
      departmentId: dept.id,
      score: Math.max(50, Math.min(99, dept.aiScore + Math.floor(Math.random() * 20 - 10))),
      reason: `基于AI综合评分分析，${dept.hospital} ${dept.name}在"${trimmed}"相关病例中具备${dept.specialties[0]}等核心能力。`,
    }))
    .sort((a, b) => b.score - a.score);
}
