import type { Patient, PatientDiagnosis, MDTSession, PatientStatistics } from '@/types/patient';

// Mock患者数据
export const mockPatients: Patient[] = [
  {
    id: '1',
    name: '李建国',
    admissionNumber: 'ZY2023051289',
    gender: '男',
    age: 68,
    birthDate: '1955-03-15',
    ethnicity: '汉族',
    maritalStatus: '已婚',
    occupation: '退休工人',
    phone: '138****5678',
    emergencyContact: {
      name: '李小红',
      relation: '女儿',
      phone: '139****8765',
    },
    address: '北京市海淀区XX街道XXX巷XX号3楼5单元101',
    department: '肺外科',
    ward: '3病区',
    bed: '12床',
    admissionDate: '2023-05-10',
    primaryDoctor: '张伟',
    primaryDoctorDept: '肺外科',
    primaryDiagnosis: '右肺上叶腺癌(cT2aN1M0，IIB期)',
    relatedDepartments: ['影像科', '肺外科'],
    mdtStatus: 'ongoing',
    createdAt: '2023-05-12',
    medicalSummary:
      '患者因"咳嗽咳痰3月余，发现右肺占位1周"入院。患者2月前无明显诱因出现咳嗽、咳痰，为白色黏痰，量不多，无痰中带血，无发热、胸闷、气短等症状。1周前于当地医院行胸部CT检查示：右肺上叶占位。',
    pastHistory:
      '既往史：有高血压病史10年，最高血压160/95mmHg，规律服用降压药控制，血压控制尚可。否认糖尿病、冠心病史。否认肝炎、结核病史。否认手术外伤史。',
    admissionVitals:
      '入院体征：T 36.5℃，P 82次/分，R 18次/呼吸，BP 135/85mmHg。神志清，精神可，呼吸平，查体配合。双肺呼吸音清，未闻及明显干湿性啰音。心律齐，各瓣膜听诊区未闻及杂音。腹平软，无压痛、反跳痛，肝脾未触及。双下肢无水肿。',
  },
  {
    id: '2',
    name: '王秀兰',
    admissionNumber: 'ZY2023051045',
    gender: '女',
    age: 54,
    birthDate: '1969-08-22',
    ethnicity: '汉族',
    maritalStatus: '已婚',
    occupation: '教师',
    phone: '136****1234',
    emergencyContact: {
      name: '王强',
      relation: '丈夫',
      phone: '137****5678',
    },
    address: '北京市朝阳区XX路XX号',
    department: '肿瘤科',
    ward: '2病区',
    bed: '8床',
    admissionDate: '2023-05-08',
    primaryDoctor: '李明',
    primaryDoctorDept: '外科',
    primaryDiagnosis: '胃癌术后化疗方案',
    relatedDepartments: ['外科', '肿瘤科'],
    mdtStatus: 'completed',
    createdAt: '2023-05-10',
    medicalSummary: '患者胃癌术后，需制定后续化疗方案。',
    pastHistory: '否认高血压、糖尿病病史。',
    admissionVitals: 'T 36.8℃，P 78次/分，R 16次/呼吸，BP 120/80mmHg。',
  },
  {
    id: '3',
    name: '张伟明',
    admissionNumber: 'ZY2023050912',
    gender: '男',
    age: 72,
    birthDate: '1951-12-05',
    ethnicity: '汉族',
    maritalStatus: '已婚',
    occupation: '退休干部',
    phone: '135****9876',
    emergencyContact: {
      name: '张丽',
      relation: '女儿',
      phone: '138****4321',
    },
    address: '北京市西城区XX街XX号',
    department: '肝胆外科',
    ward: '1病区',
    bed: '15床',
    admissionDate: '2023-05-07',
    primaryDoctor: '赵医生',
    primaryDoctorDept: '主治',
    primaryDiagnosis: '肝占位性病变',
    relatedDepartments: ['主治', '肝胆外科'],
    mdtStatus: 'not_started',
    createdAt: '2023-05-09',
    medicalSummary: '患者发现肝占位性病变，需进一步诊断。',
    pastHistory: '有糖尿病病史5年。',
    admissionVitals: 'T 37.0℃，P 80次/分，R 18次/呼吸，BP 140/90mmHg。',
  },
  {
    id: '4',
    name: '张丽华',
    admissionNumber: 'ZY2023050876',
    gender: '女',
    age: 45,
    birthDate: '1978-03-18',
    ethnicity: '汉族',
    maritalStatus: '已婚',
    occupation: '会计',
    phone: '139****2468',
    emergencyContact: {
      name: '刘强',
      relation: '丈夫',
      phone: '138****1357',
    },
    address: '北京市东城区XX路XX号',
    department: '乳腺外科',
    ward: '4病区',
    bed: '6床',
    admissionDate: '2023-05-06',
    primaryDoctor: '孙医生',
    primaryDoctorDept: '超检',
    primaryDiagnosis: '乳腺癌综合治疗',
    relatedDepartments: ['超检', '乳腺外科'],
    mdtStatus: 'ongoing',
    createdAt: '2023-05-08',
    medicalSummary: '患者乳腺癌确诊，需制定综合治疗方案。',
    pastHistory: '无特殊病史。',
    admissionVitals: 'T 36.6℃，P 75次/分，R 16次/呼吸，BP 118/75mmHg。',
  },
  {
    id: '5',
    name: '陈志强',
    admissionNumber: 'ZY2023050732',
    gender: '男',
    age: 58,
    birthDate: '1965-07-12',
    ethnicity: '汉族',
    maritalStatus: '已婚',
    occupation: '工程师',
    phone: '137****8642',
    emergencyContact: {
      name: '陈芳',
      relation: '妻子',
      phone: '136****9753',
    },
    address: '北京市丰台区XX街XX号',
    department: '胃肠外科',
    ward: '2病区',
    bed: '20床',
    admissionDate: '2023-05-05',
    primaryDoctor: '周医生',
    primaryDoctorDept: '手术',
    primaryDiagnosis: '结直肠术后复查',
    relatedDepartments: ['手术', '胃肠外科'],
    mdtStatus: 'completed',
    createdAt: '2023-05-07',
    medicalSummary: '患者结直肠术后，定期复查。',
    pastHistory: '有高血压病史8年。',
    admissionVitals: 'T 36.7℃，P 76次/分，R 17次/呼吸，BP 130/85mmHg。',
  },
];

// Mock诊断信息
export const mockDiagnoses: PatientDiagnosis[] = [
  {
    id: '1',
    patientId: '1',
    type: '主要诊断',
    name: '右肺上叶腺癌(cT2aN1M0，IIB期)',
    date: '2023-05-12',
  },
  {
    id: '2',
    patientId: '1',
    type: '其他诊断',
    name: '高血压2级（很高危组）',
    date: '2023-05-10',
  },
  {
    id: '3',
    patientId: '1',
    type: '其他诊断',
    name: '2型糖尿病',
    date: '2023-05-10',
  },
];

// Mock MDT会诊信息
export const mockMDTSessions: MDTSession[] = [
  {
    id: '1',
    code: 'MDT-20230513-008',
    patientId: '1',
    applicantDept: '肺胸科',
    host: '李明',
    hostTitle: '主任医师',
    startTime: '2023-05-13 14:00',
    participatingDepts: ['影像科', '病理科', '外科', '内科'],
    status: 'ongoing',
  },
];

// Mock统计数据
export const mockPatientStatistics: PatientStatistics = {
  total: 128,
  totalChange: 12,
  ongoingMDT: 12,
  ongoingMDTNew: 3,
  completedMDT: 86,
  completedMDTChange: 8,
  notStartedMDT: 30,
};

// 科室列表
export const mockDepartments = [
  '全部科室',
  'MDT科室',
  '影像科',
  '病理科',
  '外科',
  '内科',
  '肺外科',
  '肿瘤科',
  '肝胆外科',
  '乳腺外科',
  '胃肠外科',
];

// 病种列表
export const mockDiseases = [
  '全部病种',
  '肺癌',
  '胃癌',
  '肝癌',
  '乳腺癌',
  '结直肠癌',
];
